[package]
name = "flowcontrol"
version = "0.1.0"
edition = "2021"
description = "Utilities for clarifying and simplifying control flow"
readme = "readme.md"
repository = "https://github.com/andrewbaxter/flowcontrol"
license = "ISC"

[dependencies]
